### PR TITLE
added a pokedex class

### PR DESCRIPTION
**Pull request by obiben**
Hey there,

Nice library!

Added a Pokedex class so we can easily get pokemon names for printing. Also included rarity in there, and used that to make the demo bot smarter.

Didn't experiment too much with speeds, but I lowered it arbitrarily so the bot would actually hatch eggs rather than being considered too fast for walking.

Made the step-by-step log be debug level so there would be less spam in the console.

### CODE REVIEW

**Comment by dmadisetti** [comment]
Stable enough to test yet?

**Comment by obiben** [comment]
Yep, using it at the moment, the oops commit was just a problem with the bot not keeping track of the rarest pokemon found.

**Comment by obiben** [comment]
Ignoring the "CRITTER" category is kinda nice! Any other common you think should be moved there? Pretty sure some others could qualify

**Comment by dmadisetti** [comment]
Nice! I think it's pretty solid. I think I will revert automatically starting the simple bot, since this is first and foremost an api

**Comment by dmadisetti** [comment]
Just out of curiosity, how did you determine 3.2 as walking?

**Comment by obiben** [comment]
Completely arbitrary, sounded like a speed you could run at. Haven't tested the limits of what will fill up incubator time and what wont - I'll do that next time I fiddle around with it.

This is pretty much an excuse for me to fiddle with AI, so next PR will most likely be a better bot - I'll make sure I keep your demo intact and use a different file for starting my bot.

By the way, have you ever gotten an account banned for using this - and if so did you find some sort of limit?

**Comment by dmadisetti** [comment]
I've only ever gotten banned for jumping. eg San Francisco -> NY in a few minutes

**Comment by dmadisetti** [comment]
Hmm. We'll have to test the speed a bit more. 7.5 has been working towards eggs. It's a reasonable biking speed

**Comment by obiben** [comment]
Oh yeah? I was under the impression it didn't. Could just be me! I'll do some testing for sure.

**Comment by dmadisetti** [comment]
@obiben Made some changes for better botting and reworked pokedex https://github.com/rubenvereecken/pokemongo-api/tree/bot

**Pull request merged**
