### PR TITLE
Proper Packaging (for installation via pip)

### PR DESCRIPTION
**Pull request by TechnicalBro**
When I discovered the project I looked at open issues, as you do, and found Issue #23. This is fixed today!

The API had to undergo major refactoring, which, unless an application rely's specifically on the POGOProtos that it generated will not cause an issue.

I moved the POGOProtos to their own package respectively, to reduce the risk of having a volatile code-base, or a messy project.

All of the relative imports are no longer relative, they are absolute, package-based imports.

There's a small fix in here regarding the parsing of locations via long/lat/alt coordinates in here as well, as I thought it was a necessary evil. Came up during my unit tests for an app I'm making and decided to include it.

Going forward this structure must be maintained, and the use of relative imports cannot happen in order to preserve the integrity of the project.

For an example, and to simply define the approach, I versioned this as "0.0.1" though I do not believe this is the state of the project, and would prefer discussion to solidify it.

### CODE REVIEW

**Comment by rubenvereecken** [comment]
Aww shit @TechnicalBro that's awesome.

I actually wanted to suggest a different approach with the protobufs though. For Node, I started a Node wrapper around the protobufs. I'd like to do the same with this so we can simply maintain that separately and do without all the hassle. I'll check that out tonight.

**Comment by rubenvereecken** [comment]
Hey @TechnicalBro, think you could give this baby a little rebase? Too scared of breaking it while merging it in.

**Comment by Dracon23** [comment]
Is there a package I could test? ;F Willing to break things if neccessary, I'm not knownledgeable enough to package this myself though :F

**Comment by rubenvereecken** [comment]
Yeah definitely @Dracon23, just clone @TechnicalBro's branch and try it out by doing `pip install .` inside (I'm guessing!)

**Comment by dmadisetti** [comment]
Pretty far behind, may cherry pick

**Comment by TechnicalBro** [comment]
Sorry @rubenvereecken for the delay in communication! Ive been out on vacation for the last 10 days! Ill rebase and push soon.

**Comment by dmadisetti** [comment]
@TechnicalBro I have a branch coming in that uses some of your changes, https://github.com/rubenvereecken/pokemongo-api/pull/86

Code base has changed a fair bit

**Pull request closed without merging**
