### PR TITLE
Added NicknamePokemon

### PR DESCRIPTION
**Pull request by DeastinY**

### CODE REVIEW

**Comment by dmadisetti** [comment]
Looks good. Will merge in this afternoon, but where did the generated proto come from?

**Comment by DeastinY** [comment]
It's an issue with https://github.com/AeonLucid/POGOProtos/ 
https://github.com/AeonLucid/POGOProtos/pull/38

**Comment by rubenvereecken** [comment]
It's useful being a contributor in both repositories :). I like it

**Comment by dmadisetti** [comment]
Will merge in new protos then

**Comment by dmadisetti** [comment]
Confirmed, waiting to do regression testing since currently softbanned
image

**Pull request merged**
