### PR TITLE
Break apart demo into Trainer + allow for pip installation

### PR DESCRIPTION
**Pull request by dmadisetti**
Rebased @obiben's experimental branch into pip happy and code current. It's a big change, so will sit on it until I have a better means of testing, or I have a peer reviewed consensus of goodness

### CODE REVIEW

**Comment by TechnicalBro** [comment]
This seems great!

The only suggestion I have is to either write tests (preferable using nosetests, as it's quite easy) to cover this code.

I'm actually going to close my previous pull request and continue with yours, as the changes you've made are actually what I was aiming for.

I'd suggest this is migrated into the main code base then re-factored down the line. It's good!

Great work!

**Comment by dmadisetti** [comment]
Great. I can get behind that. Testing will be difficult since this needs to be run against the niantic servers.

Maybe modify the requests module in the test env to feed in fake responses? 
Any other ideas?

**Comment by obiben** [comment]
I haven't been touching this for a while, but one thing that would be useful is to store what is considered a "Malformed response" into some friendly json file for further inspection, so that when testing with fake reponses, we can incorporate those into the mix.

**Comment by obiben** [comment]
The server URLs would need to be injected for tests to work, and be replaced by a local server.

Or is there such a thing as a test server that already exists and replicates pogo's servers? If not, there's a neat SaaS project!

**Comment by TechnicalBro** [comment]
I believe that the best approach would be using a mock-framework; We aren't able to exactly verify 100% the responses of the server, as we have no mock server / test server to go against which would output the proper responses, though we can test how the application would perform under circumstance. 

By that, I simply mean simulate what would be expected to be returned, such as a successful login / credentials and then follow with invalid credentials, etc.

It's behaviour driven testing, and It's quite effective!

**Pull request merged**
